---                                                                    
title: "An example of how to proc some flow cyto data - specifically DNA content staining with sytoxgreen"
author: "Darach Miller"                                                   
date: "`r Sys.Date()`"                                                    
output:                                                                   
  html_document:                                                          
    self_contained: true                                                  
---                           

# Data readin

```{r, warning=F, cache=F}
require(ggplot2)
require(flowCore)
```

```{r,warning=F,cache=T}
if (length(dir("./exp154sytoxgreen/"))) {
  directories <- c(
      exp154sytoxgreen= "./exp154sytoxgreen/"
    ) 
}
directories
dir(directories[1])
```

```{r,warning=F,cache=T}
datz <- list()  # Here's a blank list to store raw data
for (expr in names(directories)) { # For every experiment name (one)
  dirz <- directories[expr]
  for (fz in dir(dirz)[grep("fcs",dir(dirz))]) { 
      # For every FCS in that directory
    if (grepl("(water)|(h2o)|(decon)|(pbs)",fz)) {next}
      # I don't want any samples with these words...
    nameToSaveAs <- paste0(expr, warning=F,"_",sub(".fcs","",fz))
      # I'm just making a short name to name the list position 
    print(paste0("doing ",dirz,"",fz,", saving it as ",nameToSaveAs))
      # Always good to say what's up
    datz[[nameToSaveAs]] <- data.frame(
        exprs(read.FCS(paste0(dirz,fz),transformation=FALSE))
      )
  }
}
```

Here we immediately use `flowCore` just to extract the measurements 
from the machine. Note the lack of any confounding transformation.
This is 2016, and I'm pretty sure these are linear digital detectors.

The below takes everything in `datz` and `rbind()`'s it together
to make one large data frame. This might take a while.

```{r,warning=F,cache=T}
if (exists("lrgdf")) {rm(lrgdf)}
  # If it exists, remove it
for (fz in names(datz)) {
  relevantBit <- gsub(".+?\\s(.+?)$","\\1",fz)
    # Here we just take out the name of the sample
  if (!exists("lrgdf")) {
    lrgdf <- data.frame(datz[[as.character(fz)]],
      colsplit(relevantBit,"_",
        names=c("sample","dye","pretreatment")))
    # if it doesn't exist, define a new data frame
  } else {
    lrgdf <- rbind(lrgdf,data.frame(datz[[as.character(fz)]],
      colsplit(relevantBit,"_",
        names=c("sample","dye","pretreatment"))))
    # if not, then just bind the data.frame onto the previous
  }
}
dim(lrgdf)
```

Now that we have that, we can 

```{r, warning=F, cache=F,error=F}
ggplot(lrgdf[sample(1:nrow(lrgdf),1e5),])+theme_bw()+
  aes(x=log(FSC.A),y=log(FSC.H))+facet_grid(sample~pretreatment)+
  geom_point(size=.5,alpha=.005)

ggplot(lrgdf[sample(1:nrow(lrgdf),1e5),])+theme_bw()+
  aes(x=log(FSC.A),y=log(FL1.A))+facet_grid(pretreatment~sample)+
  geom_point(size=.5,alpha=.005)+
  geom_hline(yintercept=13,linetype="dashed")

subdf <- subset(lrgdf,log(FL1.A)>13&pretreatment!="neg")

ggplot(subset(subdf)[sample(1:nrow(subdf),1e5),])+theme_bw()+
  aes(x=log10(FL1.A),color=pretreatment)+
  facet_wrap(~sample)+
  stat_bin(aes(y = ..density..),binwidth=0.005,geom="line",
    position="identity",cex=.5)+
  stat_bin(aes(y = ..density..),binwidth=0.005,geom="point",
    position="identity",cex=.2)+
  theme(legend.position="bottom")

g <- ggplot(subset(subdf,pretreatment=="rnase_pk"))+theme_bw()+
  aes(x=log10(FSC.H),y=log10(FL1.H))+facet_wrap(~sample)+
  geom_point(size=0.1,alpha=.010)+
  xlab("log10(FSC.H), approx cell size")+
  ylab("log10(FL1.H), approx DNA content")+
  xlim(4.25,6.5)+ylim(5.9,6.5)
g
#ggsave("/home/zed/lab/outz/figz/160108exp154fl1hfsch.png",g,
#  width=6,height=6)
g <- ggplot(subset(subdf,pretreatment=="rnase_pk"))+theme_bw()+
  aes(x=log10(FL1.H))+
  facet_wrap(~sample)+
  stat_bin(aes(y = ..density..),binwidth=0.005,geom="line",
    position="identity",cex=.5)+
  stat_bin(aes(y = ..density..),binwidth=0.005,geom="point",
    position="identity",cex=.2)+
  theme(legend.position="bottom")+
  xlim(5.90,6.5)
g
#ggsave("/home/zed/lab/outz/figz/160108exp154fl1hdensity.png",g,
#  width=6,height=6)

```
